Repository slaclab/surf, pull requests merged in 2020-12, with the labels that each got.

#752 Remove rawWrite and rawRead from various modules
  python/surf/devices/micron/_AxiMicronMt28ew.py
  python/surf/devices/micron/_AxiMicronN25Q.py
  python/surf/devices/micron/_AxiMicronP30.py
  python/surf/devices/silabs/_Si5345.py
  python/surf/devices/silabs/_Si5345Lite.py
  python/surf/devices/silabs/_Si5345Pages.py
  python/surf/devices/ti/_Adc32Rf45.py
  python/surf/devices/ti/_Ads54J60.py
Labels: enhancement

#773 Pgp2bAxi.py Update
  python/surf/protocols/pgp/_Pgp2bAxi.py
Labels: enhancement

#774 Convert Travis to github actions
  .github/workflows/surf_ci.yml
  .travis.yml
  Doxyfile
  README.md
  conda-recipe/conda_build_config.yaml
Labels: enhancement

#776 flake8 bug fixes after upgrading to pyflakes: 2.2.0
  .github/workflows/surf_ci.yml
  python/surf/misc/_McsReader.py
  python/surf/protocols/clink/_UartOpal1000.py
Labels: bug

#775 Release Candidate v2.12.1
  .github/workflows/surf_ci.yml
  .travis.yml
  Doxyfile
  README.md
  conda-recipe/conda_build_config.yaml
  python/surf/misc/_McsReader.py
  python/surf/protocols/clink/_UartOpal1000.py
Labels: Release

#780 Make github actions script more generic for copying
  .github/workflows/surf_ci.yml
Labels: enhancement
