Repository slaclab/surf, pull requests merged in 2021-01, with the labels that each got.

#783 Add apt-get update to CI
  .github/workflows/surf_ci.yml
Labels: bug

#785 Bugfix eth packet loss
  base/general/rtl/Crc32Parallel.vhd
  ethernet/EthMacCore/rtl/EthMacRxCsum.vhd
  ethernet/EthMacCore/tb/EthMacFastTb.vhd
  ethernet/UdpEngine/rtl/UdpEngineArp.vhd
Labels: bug

#788 Updating SRPv3 for Footer.BIT13 = HwBusLockup error
  protocols/srp/rtl/SrpV3AxiLite.vhd
  protocols/srp/rtl/SrpV3Core.vhd
Labels: enhancement

#789 whitespace removal
  ethernet/EthMacCore/tb/EthMacFastTb.vhd
Labels: enhancement

#787 clean up of the SrpV3AxiLiteTb.vhd
  protocols/srp/tb/SrpV3AxiLiteTb.vhd
Labels: enhancement

#786 Release Candidate v2.12.3
  base/general/rtl/Crc32Parallel.vhd
  ethernet/EthMacCore/rtl/EthMacRxCsum.vhd
  ethernet/EthMacCore/tb/EthMacFastTb.vhd
  ethernet/UdpEngine/rtl/UdpEngineArp.vhd
  protocols/i2c/rtl/I2cMaster.vhd
  protocols/i2c/rtl/I2cPkg.vhd
  protocols/i2c/rtl/I2cRegMaster.vhd
  protocols/i2c/sim/i2cRegMasterSimPkg.vhd
  protocols/srp/rtl/SrpV3AxiLite.vhd
  protocols/srp/rtl/SrpV3Core.vhd
  protocols/srp/tb/SrpV3AxiLiteTb.vhd
Labels: Release
